---
title: "Stacy Model"
author: "James Joyce - 205765421"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(tidymodels)
```


```{r}
setwd("RecruitingUCLA")
total_combine <- read_csv("total_combine.csv")
```


### Split the Dataset

```{r}
set.seed(1501)

reduced_combine <- total_combine %>% mutate(arm_to_wingspan = Arm / Wing)

reduced_combine <- reduced_combine[,c(-1,-2,-6,-7)]

reduced_combine$Pos <- factor(reduced_combine$Pos, levels = c("OL","IOL","DL","EDGE","TE","LB","QB","RB","WR","CB","S"))



nfl_split <- initial_split(reduced_combine, strata = Pos)
nfl_train <- training(nfl_split)
nfl_test  <- testing(nfl_split)
```


### Recipe and Creating Folds

```{r}
ridge_recipe <- recipe(Weight ~ ., data = nfl_train) %>%
    step_naomit(all_predictors(), all_outcomes()) %>% 
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors(), one_hot = FALSE)



folds <- vfold_cv(nfl_train, v = 5, strata = Weight)
```


### Fitting Linear Regression

```{r}
lm_model <- linear_reg() %>%
  set_engine("lm")

lm_workflow <- workflow() %>%
  add_model(lm_model) %>%
   add_recipe(ridge_recipe)

set.seed(123)
cv_results <- lm_workflow %>% 
  fit_resamples(
    resamples = folds,
    metrics = metric_set(rmse, rsq, mae) # Metrics to evaluate
  )

# Select best parameters based on RMSE
best_linear <- select_best(cv_results, metric = "rmse")

best_model <- cv_results %>%
  collect_metrics() %>%
  filter(.metric == "rmse") %>%
  arrange(mean) #%>%
  #slice(1)  # 
```


### Finalize Model

```{r}
library(car)
final_linear <- finalize_model(lm_model, best_linear)

final_linear_workflow <- workflow() %>%
  add_model(final_linear) %>%
  add_recipe(ridge_recipe)


lm_fit <- final_linear_workflow %>% fit(nfl_train)

lm_predictions <- predict(lm_fit, nfl_test) %>%
  bind_cols(nfl_test)

fitted_lm <- lm_fit %>%
  extract_fit_parsnip() %>%
  pluck("fit")

vif_values <- vif(fitted_lm)

# Print VIF values
print(vif_values)

glance(lm_fit)

lm_fit %>% extract_fit_engine()

predictions_summary <- lm_predictions %>%
  summarize(
    mean_pred = mean(.pred, na.rm = TRUE),
    sd_pred = sd(.pred, na.rm = TRUE),
    min_pred = min(.pred, na.rm = TRUE),
    max_pred = max(.pred, na.rm = TRUE),
    mean_residual = mean(Weight - .pred, na.rm = TRUE),
    sd_residual = sd(Weight - .pred, na.rm = TRUE)
  )
print(predictions_summary)
```


### Plotting the Residuals

```{r}
head(total_combine)
      #                                                                 Arm/Wingspan
new_prediction <- data_frame(Height = 76, Hand = 9.5, arm_to_wingspan = 31.125/76, Pos = "OL")

predict(lm_fit, new_data = new_prediction)
```


